name: dynamics-client
baseurl: /dynamics-client
description: A Microsoft Dynamics CLI swiss-army knife and browser/server library.
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.1-M6
org: ttg
markdown: kramdown
